title: Felix Geisendörfer
url: http://felixge.de
author:
  name: Felix Geisendörfer
  uri: http://felixge.de/
timezone: UTC
markdown: redcarpet
highlighter: pygments
exclude:
  - NEXT.md
plugins:
  - jekyll-less
  - jekyll-redirect-from
redcarpet:
    extensions: ["footnotes"]
