[build]
  command = "hugo --gc --minify"
  publish = "public"
[context.production.environment]
  HUGO_VERSION = "0.74.3"
  HUGO_ENV = "production"

[context.deploy-preview]
  command = "hugo --gc --minify --buildFuture --buildDrafts -b $DEPLOY_PRIME_URL"
[context.deploy-preview.environment]
  HUGO_VERSION = "0.74.3"
